"""add org billing fields

Revision ID: 106db2df079a
Revises: 0008_phase3_audit_and_rate_limit
Create Date: 2026-01-25 00:04:29.403255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "106db2df079a"
down_revision = '0008_phase3_audit_and_rate_limit'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_counters')
    op.alter_column('api_keys', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_keys', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_api_keys_blocked_until', table_name='api_keys')
    op.drop_index('ix_api_keys_org', table_name='api_keys')
    op.drop_index('ix_api_keys_project', table_name='api_keys')
    op.drop_index('ux_api_keys_org_name', table_name='api_keys')
    op.create_unique_constraint(None, 'api_keys', ['id'])
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_keys', 'key_hash')
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_audit_org_action_created', table_name='audit_logs')
    op.drop_index('ix_audit_org_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_org_created', table_name='audit_logs')
    op.drop_index('ix_audit_org_resource', table_name='audit_logs')
    op.create_unique_constraint(None, 'job_run_costs', ['id'])
    op.create_unique_constraint(None, 'job_run_energy', ['id'])
    op.create_unique_constraint(None, 'job_run_hardware', ['id'])
    op.create_unique_constraint(None, 'job_run_tags', ['id'])
    op.drop_index('ix_job_runs_org', table_name='job_runs')
    op.drop_index('ix_job_runs_project_start_time', table_name='job_runs')
    op.create_unique_constraint(None, 'job_runs', ['id'])
    op.drop_constraint('fk_job_runs_organization', 'job_runs', type_='foreignkey')
    op.create_foreign_key(None, 'job_runs', 'organizations', ['organization_id'], ['id'])
    op.create_unique_constraint(None, 'model_versions', ['id'])
    op.create_unique_constraint(None, 'models', ['id'])
    op.alter_column('optimization_suggestions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('optimization_suggestions', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('optimization_suggestions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('optimization_suggestions', 'hash_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('optimization_suggestions', 'engine_version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('optimization_suggestions', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_suggestions_hash_key', table_name='optimization_suggestions')
    op.drop_index('ix_suggestions_project_status', table_name='optimization_suggestions')
    op.create_unique_constraint('ux_suggestions_hash', 'optimization_suggestions', ['hash_key'])
    op.create_unique_constraint(None, 'optimization_suggestions', ['id'])
    op.drop_column('optimization_suggestions', 'effort')
    op.drop_index('ux_org_members_org_user', table_name='organization_members')
    op.create_unique_constraint('ux_org_members_org_user', 'organization_members', ['organization_id', 'user_id'])
    op.create_unique_constraint(None, 'organization_members', ['id'])
    op.drop_constraint('organization_members_organization_id_fkey', 'organization_members', type_='foreignkey')
    op.drop_constraint('organization_members_user_id_fkey', 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('job_runs_limit', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('projects_limit', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('users_limit', sa.Integer(), nullable=True))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index('ix_projects_org', table_name='projects')
    op.drop_index('ux_projects_org_name', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['id'])
    op.alter_column('region_emission_factors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('region_emission_factors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'region_emission_factors', ['id'])
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'reports', ['id'])
    op.create_foreign_key(None, 'reports', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='unique')
    op.alter_column('reports', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'region_emission_factors', type_='unique')
    op.alter_column('region_emission_factors', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('region_emission_factors', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('ux_projects_org_name', 'projects', ['organization_id', 'name'], unique=True)
    op.create_index('ix_projects_org', 'projects', ['organization_id'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'users_limit')
    op.drop_column('organizations', 'projects_limit')
    op.drop_column('organizations', 'job_runs_limit')
    op.drop_column('organizations', 'razorpay_payment_id')
    op.drop_column('organizations', 'subscription_started_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key('organization_members_user_id_fkey', 'organization_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('organization_members_organization_id_fkey', 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'organization_members', type_='unique')
    op.drop_constraint('ux_org_members_org_user', 'organization_members', type_='unique')
    op.create_index('ux_org_members_org_user', 'organization_members', ['organization_id', 'user_id'], unique=True)
    op.add_column('optimization_suggestions', sa.Column('effort', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'optimization_suggestions', type_='unique')
    op.drop_constraint('ux_suggestions_hash', 'optimization_suggestions', type_='unique')
    op.create_index('ix_suggestions_project_status', 'optimization_suggestions', ['project_id', 'status'], unique=False)
    op.create_index('ix_suggestions_hash_key', 'optimization_suggestions', ['hash_key'], unique=False)
    op.alter_column('optimization_suggestions', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('optimization_suggestions', 'engine_version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('optimization_suggestions', 'hash_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('optimization_suggestions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('optimization_suggestions', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('optimization_suggestions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'models', type_='unique')
    op.drop_constraint(None, 'model_versions', type_='unique')
    op.drop_constraint(None, 'job_runs', type_='foreignkey')
    op.create_foreign_key('fk_job_runs_organization', 'job_runs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'job_runs', type_='unique')
    op.create_index('ix_job_runs_project_start_time', 'job_runs', ['project_id', 'start_time'], unique=False)
    op.create_index('ix_job_runs_org', 'job_runs', ['organization_id'], unique=False)
    op.drop_constraint(None, 'job_run_tags', type_='unique')
    op.drop_constraint(None, 'job_run_hardware', type_='unique')
    op.drop_constraint(None, 'job_run_energy', type_='unique')
    op.drop_constraint(None, 'job_run_costs', type_='unique')
    op.create_index('ix_audit_org_resource', 'audit_logs', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_org_actor_created', 'audit_logs', ['organization_id', 'actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_org_action_created', 'audit_logs', ['organization_id', 'action', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('api_keys', sa.Column('key_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_index('ux_api_keys_org_name', 'api_keys', ['organization_id', 'name'], unique=True)
    op.create_index('ix_api_keys_project', 'api_keys', ['project_id'], unique=False)
    op.create_index('ix_api_keys_org', 'api_keys', ['organization_id'], unique=False)
    op.create_index('ix_api_keys_blocked_until', 'api_keys', ['blocked_until'], unique=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_keys', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('api_keys', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('rate_limit_counters',
    sa.Column('key', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='rate_limit_counters_pkey')
    )
    # ### end Alembic commands ###
